# Generated by Django 4.2.7 on 2024-02-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kategorije', models.CharField(max_length=5)),
                ('naziv_kategorije', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_korisnika', models.CharField(max_length=100)),
                ('prezime_korisnika', models.CharField(max_length=100)),
                ('adresa_korisnika', models.CharField(max_length=100)),
                ('mobitel_korisnika', models.CharField(max_length=10)),
                ('email_korisnika', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id_narudzbe', models.AutoField(primary_key=True, serialize=False)),
                ('ukupna_cijena', models.IntegerField()),
                ('narudzba_korisnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='Placanje',
            fields=[
                ('narudzba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.narudzba')),
                ('broj_kartice', models.CharField(max_length=20)),
                ('ime_kupca', models.CharField(max_length=100)),
                ('prezime_kupca', models.CharField(max_length=100)),
                ('vrijeme_placanja', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proizvoda', models.CharField(max_length=5)),
                ('naziv_proizvoda', models.CharField(max_length=100)),
                ('cijena_proizvoda', models.IntegerField()),
                ('opis_proizvoda', models.TextField()),
                ('slika_proizvoda', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('proizvod_kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proizvodi', to='main.kategorija')),
                ('proizvod_korisnik', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.korisnik')),
            ],
        ),
        migrations.AddField(
            model_name='narudzba',
            name='narudzba_proizvod',
            field=models.ManyToManyField(to='main.proizvod'),
        ),
    ]
